### ISSUE TITLE
Create a data loader

### ISSUE THREAD

**Issue by Tony911029** [Blood-Glucose-Control/t1d-change-point-detection-benchmark#12]
## TODO

- [ ] Point to the latest HF dataset once data is ready (it is currently pointing to my temp HF dataset)
- [ ] Modify the duration once the data is ready (the final data should be 6 months with a 4/1/1 split between train, test and val sets
- [ ] Remove columns when loading data as they won't exist in the latest data
- [ ] Update current numbers of patients in README

## Overview
The data loader is designed to load and split patient time-series data into training, validation, and test sets. It handles continuous patient monitoring data while maintaining temporal consistency in the splits.

## Function Signature
```python
def loader(
    data: str = "cpd",
    split: str = "train",
    patient_ids: Optional[List[str]] = None
) -> Union[Dataset, Dict[str, Dataset]]
```

### data: str (default="cpd")
Currently supports:
- "cpd": Continuous Patient Data
Future support planned for transfer learning datasets.

### split: str (default="train")
Specifies which portion of the split data to return:
- "train": Training dataset
- "val": Validation dataset
- "test": Test dataset
- "all": Returns all splits as a dictionary

### patient_ids: Optional[List[str]] (default=None)
- List of specific patient IDs to retrieve
- If None, returns data for all available patients
- Must be a list of valid patient identifiers

### For split="train", "test", or "val":
Returns a single Dataset with shape (#patients, #days)

### For split="all":
Returns a dictionary containing all three splits:
```python
{
    "train": Dataset,  # shape: (#patients, #days)
    "val": Dataset,    # shape: (#patients, #days)
    "test": Dataset    # shape: (#patients, #days)
}
```

### Split Ratios for a 6-month data
- Training: 4 months
- Validation: 1 month
- Test: 1 month
